services:
  strapi:
    image: ghcr.io/almatn/tours-strapi:latest
    depends_on:
      - strapi-db
    env_file:
      - strapi/.env.prod
    networks:
      - buybuy_default
    volumes:
      - tours_media_strapi:/app/public/uploads

  strapi-db:
    image: postgres:16-bookworm
    env_file:
      - .env.production
    volumes:
      - pgdatastrapi:/var/lib/postgresql/data
    networks:
      - buybuy_default

  strapi-frontend:
    image: ghcr.io/almatn/tours-frontend:latest
    env_file:
      - .env.production
    depends_on:
      - strapi
    networks:
      - buybuy_default
    
volumes:
  pgdatastrapi:
  tours_media_strapi:
    name: tours_media_strapi

networks:
  buybuy_default:
    external: true
