services:
  strapi:
    image: ghcr.io/almatn/tours-strapi:latest
    ports:
      - "1337:1337"
    depends_on:
      - strapi-db
    env_file:
      - .env.production
    networks:
      - buybuy_default

  strapi-db:
    image: postgres:16-bookworm
    env_file:
      - .env.production
    volumes:
      - pgdatastrapi:/var/lib/postgresql/data
    networks:
      - buybuy_default

  strapi-frontend:
    image: ghcr.io/almatn/tours-frontend:latest
    ports:
      - "3100:3100"
    env_file:
      - .env.production
    depends_on:
      - strapi
    networks:
      - buybuy_default
    
volumes:
  pgdatastrapi:

networks:
  buybuy_default:
    external: true
