services:
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - strapi-db
    env_file:
      - .env.production
    networks:
      - buybuy_default

  strapi-db:
    image: postgres:16-bookworm
    env_file:
      - .env.production
    volumes:
      - pgdatastrapi:/var/lib/postgresql/data
    networks:
      - buybuy_default

  strapi-frontend:
    ports:
      - "3100:3100"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env.production
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
      - ./frontend/postcss.config.js:/frontend/postcss.config.js
      - ./frontend/postcss.config.mjs:/frontend/postcss.config.mjs
      - ./frontend/tailwind.config.js:/frontend/tailwind.config.js
      - ./frontend/tailwind.config.ts:/frontend/tailwind.config.ts
    depends_on:
      - strapi
    networks:
      - buybuy_default

volumes:
  pgdatastrapi:

networks:
  buybuy_default:
    external: true